name: Tempalte
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          cd build/
          cmake ..; make

      - name: Run tests
        run: |
         ./build/src/main

